name: sqflite_web
homepage: https://github.com/tekartik/sqflite/tree/master/sqflite_web
description: sqflite web implementation (without database persistency)
version: 2.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: SqflitePluginWeb
        fileName: sqflite_web.dart

  # TODO: Those assets should only be on Web platform but this is not yet handled by Flutter
  # https://github.com/flutter/flutter/issues/8230
  assets:
    - packages/sqflite_web/assets/require.js
    - packages/sqflite_web/assets/sqflite_web.js

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  plugin_platform_interface: ^2.0.0

  # For Sqflite 'subplugin' compatibility
  sqflite_common: ^2.0.0
  synchronized: ^3.0.0
  path: ^1.8.0
  meta: ^1.3.0

  # For Web implementation compatibility
  js: ^0.6.3

dev_dependencies:
  flutter_lints: ^1.0.0
  test:
  process_run: '>=0.10.7'
